spring.application.name=external-api-service

tmdb.bearer.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlZWRhY2YzYzU4YWQ3MmU5MjRhNTlkNTY5YTY3ZWQyYiIsInN1YiI6IjY2NDhjYWY1NzgxYzRiMjlmYjc4YzI5NCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.cWVnFFOWMWsffX9rRwC0ZAM39lqtaFWQ5-p3g6fgUVM

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.platform=h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.h2.console.settings.web-allow-others=true

